// @ts-nocheck
import { useState } from 'react'
import { ArrowUpRight, Check, Copy, Download, ExternalLink, FileText, Landmark, Pencil, Plus, Send, ShieldAlert, ShieldCheck, Trash2, WalletCards, X } from 'lucide-react'
import './investor-funds.css'
import './funds-enhancements.css'
import './funds-density.css'
import './funds-wallet-setup.css'
import './funds-motion.css'
import './funds-layout-fix.css'

const initialWallets = [
  { id: 'w1', name: 'Основной USDT', network: 'TRC-20', address: 'TQ9x...84F2', primary: true, description: 'Основной кошелёк для свободного баланса и пополнения escrow.', usage: 'Свободный баланс · 4 230,00 USDT', balance: '4 230,00', values: [3200, 3420, 3350, 3660, 3910, 4020, 4230] },
  { id: 'w2', name: 'Ethereum', network: 'ERC-20', address: '0x8A2F...7B10', description: 'Резервный кошелёк для операций в сети Ethereum.', usage: 'Не задействован в договорах', balance: '1 860,00', values: [1740, 1790, 1760, 1830, 1810, 1880, 1860] },
]
const escrow = [
  { id: 'e1', name: 'Orion Capital Strategy', balance: '7 500,00', coverage: 164, contract: 'BRK-OR-2026-014', events: [['Пополнение залога', '+5 000,00 USDT', '06 авг 2026'], ['Начисление комиссии', '−420,00 USDT', '01 авг 2026']] },
  { id: 'e2', name: 'Alpha Quant Strategy', balance: '3 000,00', coverage: 146, contract: 'BRK-AQ-2026-009', events: [['Пополнение залога', '+2 000,00 USDT', '20 июл 2026']] },
  { id: 'e3', name: 'Delta Diversified Strategy', balance: '2 000,00', coverage: 96, contract: 'BRK-DD-2026-021', events: [['Начисление комиссии', '−310,00 USDT', '06 авг 2026'], ['Проверка покрытия', '96%', '06 авг 2026']] },
]
const history = [
  { id: 'tx1', title: 'Пополнение escrow', target: 'Orion Capital Strategy', amount: '+5 000,00 USDT', date: '06 авг 2026', status: 'Исполнено', network: 'TRC-20', hash: 'af4b91e2...a8c1d490', type: 'blockchain' },
  { id: 'tx2', title: 'Начисление прибыли', target: 'Alpha Quant Strategy', amount: '+1 240,00 USDT', date: '01 авг 2026', status: 'Исполнено', network: 'Внутренний расчёт', hash: 'STL-2026-08-001', type: 'statement' },
  { id: 'tx3', title: 'Запрос на вывод', target: 'Beta Income Strategy', amount: '−1 000,00 USDT', date: '28 июл 2026', status: 'На рассмотрении', network: 'TRC-20', hash: 'wd-8e22...049f', type: 'blockchain' },
]

export function InvestorFunds() {
  const [tab, setTab] = useState('Кошельки'); const [wallets, setWallets] = useState(initialWallets); const [drawer, setDrawer] = useState(null); const [toast, setToast] = useState(''); const [selectedWallet, setSelectedWallet] = useState('all')
  const notify = message => setToast(message)
  const wallet = drawer?.walletId ? wallets.find(item => item.id === drawer.walletId) : null
  const addWallet = data => { setWallets(items => [...items, { id: String(Date.now()), ...data, address: `${data.address.slice(0, 6)}...${data.address.slice(-4)}`, description: 'Описание ещё не добавлено.', usage: 'Не задействован в договорах', balance: '0,00', values: [0, 0, 0, 0, 0, 0, 0] }]); setDrawer(null); notify('Кошелёк добавлен') }
  const updateWallet = (id, details) => { setWallets(items => items.map(item => item.id === id ? { ...item, ...details } : item)); notify('Изменения сохранены') }
  return <main className="funds-page"><header className="funds-heading"><p>Кошельки, escrow-счета и история движения средств.</p><span>Обновлено сегодня, 10:15 (UTC+3)</span></header><div className="funds-kpis"><Metric label="СВОБОДНЫЙ БАЛАНС" value="4 230,00 USDT" note="Доступно к выводу"/><Metric label="В ESCROW" value="12 500,00 USDT" note="3 активных счёта"/><Metric label="В ИНВЕСТИЦИЯХ" value="100 000,00 USDT" note="4 стратегии"/></div><nav className="funds-tabs">{['Кошельки','Escrow-счета','История'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>setTab(item)}>{item}</button>)}</nav>{tab==='Кошельки'&&<Wallets wallets={wallets} selected={selectedWallet} select={setSelectedWallet} open={payload=>setDrawer(payload)} notify={notify}/>} {tab==='Escrow-счета'&&<Escrow open={item=>setDrawer({kind:'escrow',escrow:item})}/>} {tab==='История'&&<History open={item=>setDrawer({kind:'transaction',transaction:item})}/>} {drawer&&<Drawer data={drawer} wallet={wallet} close={()=>setDrawer(null)} openDrawer={setDrawer} addWallet={addWallet} updateWallet={updateWallet} deleteWallet={id=>{setWallets(items=>items.filter(item=>item.id!==id));setDrawer(null);notify('Кошелёк удалён')}} notify={notify} wallets={wallets}/>} {toast&&<div className="funds-toast"><Check/>{toast}<button onClick={()=>setToast('')}><X size={15}/></button></div>}</main>
}
function Metric({label,value,note}){return <div><p>{label}</p><b>{value}</b><span>{note}<ArrowUpRight/></span></div>}
function Wallets({wallets,selected,select,open}){const selectedData=selected==='all'?null:wallets.find(item=>item.id===selected);const series=selectedData?selectedData.values:wallets[0].values.map((value,index)=>value+wallets[1].values[index]);const total=selectedData?`${selectedData.balance} USDT`:'6 090,00 USDT';return <section className="funds-section"><div className="funds-insight"><div className="funds-chart"><div className="chart-copy"><p className="eyebrow">ДИНАМИКА КОШЕЛЬКОВ</p><b>{total}</b><span>{selectedData?selectedData.name:'Все кошельки'} · за 30 дней</span></div><div className="wallet-filter"><button className={selected==='all'?'active':''} onClick={()=>select('all')}>Все</button>{wallets.map(item=><button key={item.id} className={selected===item.id?'active':''} onClick={()=>select(item.id)}>{item.name}</button>)}</div><LineChart values={series}/></div><FundsSummary/></div><div className="section-top"><div><p className="eyebrow">МОИ КОШЕЛЬКИ</p><h3>Кошельки</h3></div><button className="add-wallet" onClick={()=>open({kind:'add'})}><Plus size={15}/>Добавить</button></div><div className="wallet-list">{wallets.map(item=><article className="wallet-row" key={item.id} onClick={()=>open({kind:'wallet',walletId:item.id})}><WalletCards/><div><b>{item.name}{item.primary&&<em>Основной</em>}</b><span>{item.network} · {item.address}</span></div><span className="wallet-ready"><Check/>Готов к операциям</span><div className="wallet-quick-actions"><button onClick={event=>{event.stopPropagation();open({kind:'deposit',walletId:item.id})}}>Пополнить<ArrowUpRight/></button><button onClick={event=>{event.stopPropagation();open({kind:'withdraw',walletId:item.id})}}>Вывести<ArrowUpRight/></button><button onClick={event=>{event.stopPropagation();open({kind:'transfer',walletId:item.id})}}>Перевод<Send/></button></div><ArrowUpRight className="row-arrow"/></article>)}</div></section>}
function FundsSummary(){return <aside className="funds-summary"><p className="eyebrow">СТРУКТУРА СРЕДСТВ</p><div className="summary-total"><b>116 730,00 USDT</b><span>Общая стоимость</span></div><div className="summary-split"><div><i className="free"/><span>Свободный баланс</span><b>4 230</b><small>3,6%</small></div><div><i className="escrow"/><span>Escrow</span><b>12 500</b><small>10,7%</small></div><div><i className="invested"/><span>В инвестициях</span><b>100 000</b><small>85,7%</small></div></div><div className="summary-events"><p>ПОСЛЕДНИЕ ДВИЖЕНИЯ</p><span><i/>Пополнение escrow <b>+5 000</b></span><span><i/>Начисление прибыли <b>+1 240</b></span></div></aside>}
function LineChart({values}){const min=Math.min(...values)-100,max=Math.max(...values)+100;const points=values.map((value,index)=>`${index*16.66},${92-(value-min)/(max-min)*72}`).join(' ');return <div className="funds-line"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><defs><linearGradient id="fundsFill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#a855ff" stopOpacity=".30"/><stop offset="1" stopColor="#a855ff" stopOpacity="0"/></linearGradient></defs><polyline points={`0,100 ${points} 100,100`} fill="url(#fundsFill)" stroke="none"/><polyline points={points} fill="none" stroke="#bd66ff" strokeWidth="1.1" vectorEffect="non-scaling-stroke"/></svg><div><span>7 июл</span><span>14 июл</span><span>21 июл</span><span>28 июл</span><span>6 авг</span></div></div>}
function Escrow({open}){return <section className="funds-section"><p className="eyebrow">ОБЕСПЕЧЕНИЕ КОМИССИИ</p><h3>Escrow-счета</h3><p className="subcopy">Откройте счёт, чтобы посмотреть историю залога, договор и все связанные операции.</p>{escrow.map(item=><article className={`escrow-row ${item.coverage<100?'low':''}`} key={item.id} onClick={()=>open(item)}><Landmark/><div><b>{item.name}</b><span>Залог: {item.balance} USDT · договор {item.contract}</span></div><div><p>Покрытие</p><strong>{item.coverage}%</strong><span>{item.coverage<100?'Недостаточно':'Достаточно'}</span></div>{item.coverage<100?<button className="funds-primary" onClick={event=>{event.stopPropagation();open({...item,topup:true})}}>Пополнить залог</button>:<span className="escrow-ok"><ShieldCheck/>Достаточно</span>}<ArrowUpRight className="row-arrow"/></article>)}</section>}
function History({open}){return <section className="funds-section"><p className="eyebrow">ИСТОРИЯ СРЕДСТВ</p><h3>Все движения</h3><div className="funds-history">{history.map(item=><article key={item.id} onClick={()=>open(item)}><FileText/><div><b>{item.title}</b><span>{item.target}</span></div><strong className={item.amount[0]==='+'?'positive':''}>{item.amount}</strong><time>{item.date}<small>{item.status}</small></time><ArrowUpRight/></article>)}</div></section>}
function NetworkChips({network,setNetwork}){return <div className="network-chips">{['TRC-20','ERC-20','BEP-20'].map(item=><button key={item} className={network===item?'active':''} onClick={()=>setNetwork(item)}>{item}</button>)}</div>}
function Drawer({data,wallet,close,openDrawer,addWallet,updateWallet,deleteWallet,notify,wallets}){const [amount,setAmount]=useState(''),[recipient,setRecipient]=useState(wallets.find(item=>item.id!==wallet?.id)?.id);const finish=message=>{notify(message);close()};return <div className="funds-modal"><button className="modal-backdrop" onClick={close}/><section><button className="close-drawer" onClick={close}><X/></button>{data.kind==='add'?<AddWallet addWallet={addWallet}/>:data.kind==='wallet'?<WalletDetail wallet={wallet} updateWallet={updateWallet} deleteWallet={deleteWallet} openAction={kind=>openDrawer({kind,walletId:wallet.id})} notify={notify}/>:data.kind==='escrow'?<EscrowDetail item={data.escrow} close={close} finish={finish}/>:data.kind==='transaction'?<TransactionDetail item={data.transaction} notify={notify}/>:<ActionFlow kind={data.kind} wallet={wallet} amount={amount} setAmount={setAmount} recipient={recipient} setRecipient={setRecipient} wallets={wallets} finish={finish} notify={notify}/>}</section></div>}
function AddWallet({addWallet}){const [type,setType]=useState('external'),[name,setName]=useState(''),[address,setAddress]=useState(''),[network,setNetwork]=useState('TRC-20'),[exchange,setExchange]=useState('Binance'),[apiKey,setApiKey]=useState(''),[secret,setSecret]=useState('');const external=type==='external';const ready=external?name&&address:name&&apiKey&&secret;const add=()=>addWallet(external?{name,address,network}:{name,network:exchange,address:'API подключен',description:`Биржевой аккаунт ${exchange}`,usage:'Биржевой кошелёк · доступ по API',balance:'0,00',values:[0,0,0,0,0,0,0]});return <><p className="eyebrow">НОВЫЙ КОШЕЛЁК</p><h2>Добавить кошелёк</h2><div className="wallet-type"><button className={external?'active':''} onClick={()=>setType('external')}><WalletCards/>Внешний адрес<small>Адрес в блокчейне</small></button><button className={!external?'active':''} onClick={()=>setType('exchange')}><Landmark/>Биржевой аккаунт<small>Подключение по API</small></button></div>{external?<><label>Название<input value={name} onChange={event=>setName(event.target.value)} placeholder="Например, основной USDT"/></label><label>Сеть<NetworkChips network={network} setNetwork={setNetwork}/></label><label>Адрес<input value={address} onChange={event=>setAddress(event.target.value)} placeholder="Введите адрес кошелька"/></label></>:<><label>Название подключения<input value={name} onChange={event=>setName(event.target.value)} placeholder="Например, Binance основной"/></label><label>Биржа<div className="exchange-choice">{['Binance','Bybit','OKX'].map(item=><button key={item} className={exchange===item?'active':''} onClick={()=>setExchange(item)}>{item}</button>)}</div></label><label>API Key<input value={apiKey} onChange={event=>setApiKey(event.target.value)} placeholder="Вставьте API Key"/></label><label>Secret Key<input type="password" value={secret} onChange={event=>setSecret(event.target.value)} placeholder="Вставьте Secret Key"/></label><p className="api-note"><ShieldCheck/> Нужны только права Read / Wallet Balance. Торговля и вывод через API не запрашиваются.</p></>}<button className="funds-primary" disabled={!ready} onClick={add}>Подключить кошелёк</button></>}
function WalletDetail({wallet,updateWallet,deleteWallet,openAction,notify}){const [editing,setEditing]=useState(false),[name,setName]=useState(wallet.name),[description,setDescription]=useState(wallet.description);const save=()=>{updateWallet(wallet.id,{name,description});setEditing(false)};return <><p className="eyebrow">КОШЕЛЁК</p><div className="detail-title"><h2>{wallet.name}</h2><button onClick={()=>setEditing(!editing)}><Pencil size={14}/>{editing?'Отменить':'Изменить'}</button></div><div className="wallet-drawer-address"><span>{wallet.network}</span><b>{wallet.address}</b><button onClick={()=>notify('Адрес скопирован')}><Copy size={15}/></button></div>{editing?<div className="wallet-edit"><label>Название<input value={name} onChange={event=>setName(event.target.value)}/></label><label>Описание<textarea value={description} onChange={event=>setDescription(event.target.value)}/></label><button className="text-action" onClick={save}>Сохранить изменения</button></div>:<div className="wallet-description"><p>ОПИСАНИЕ</p><span>{wallet.description||'Описание не добавлено.'}</span></div>}<div className="wallet-usage"><p>ГДЕ ИСПОЛЬЗУЕТСЯ</p><b>{wallet.usage}</b><span>Нет действующих договоров — вывод разрешён.</span></div><p className="eyebrow">ДЕЙСТВИЯ</p><div className="drawer-actions"><button onClick={()=>openAction('deposit')}><Plus/>Пополнить</button><button onClick={()=>openAction('withdraw')}><ArrowUpRight/>Вывести</button><button onClick={()=>openAction('transfer')}><Send/>Перевести</button></div><button className="delete-wallet" onClick={()=>deleteWallet(wallet.id)}><Trash2/>Удалить кошелёк</button></>}
function ActionFlow({kind,wallet,amount,setAmount,recipient,setRecipient,wallets,finish,notify}){const isDeposit=kind==='deposit',isTransfer=kind==='transfer';return <><p className="eyebrow">{isDeposit?'ПОПОЛНЕНИЕ':isTransfer?'ВНУТРЕННИЙ ПЕРЕВОД':'ВЫВОД'}</p><h2>{isDeposit?'Пополнить':isTransfer?'Перевести средства':'Вывести средства'}</h2><p className="flow-wallet">{wallet.name} · {wallet.network} · {wallet.address}</p>{isDeposit?<><div className="deposit-address"><div className="qr">▦</div><div><p>Адрес для пополнения</p><b>{wallet.address}</b><button onClick={()=>notify('Адрес для пополнения скопирован')}><Copy size={15}/>Скопировать адрес</button></div></div><p className="transfer-warning">Отправляйте только USDT в сети {wallet.network}.</p></>:<><label>{isTransfer?'Получатель':'Сумма, USDT'}{isTransfer?<div className="receiver-list">{wallets.filter(item=>item.id!==wallet.id).map(item=><button key={item.id} className={recipient===item.id?'active':''} onClick={()=>setRecipient(item.id)}>{item.name}<small>{item.network} · {item.address}</small></button>)}</div>:<input value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0,00"/>}</label>{isTransfer&&<label>Сумма, USDT<input value={amount} onChange={event=>setAmount(event.target.value)} placeholder="0,00"/></label>}<button className="funds-primary" disabled={!Number(amount)} onClick={()=>finish(isTransfer?'Внутренний перевод создан':'Запрос на вывод отправлен')}>{isTransfer?'Подтвердить перевод':'Подтвердить вывод'}</button></>}</>}
function EscrowDetail({item,close,finish}){return <><p className="eyebrow">ESCROW-СЧЁТ</p><h2>{item.name}</h2><div className="detail-pairs"><span>Договор<b>{item.contract}</b></span><span>Покрытие<b className={item.coverage<100?'amber':''}>{item.coverage}%</b></span><span>Залог<b>{item.balance} USDT</b></span></div><p className="eyebrow">ИСТОРИЯ ESCROW</p><div className="escrow-history">{item.events.map(event=><div key={event[0]}><b>{event[0]}</b><span>{event[1]} · {event[2]}</span></div>)}</div>{item.coverage<100&&<button className="funds-primary" onClick={()=>finish('Адрес escrow-счёта подготовлен')}>Пополнить залог</button>}<button className="text-action" onClick={()=>finish('Открыт договор '+item.contract)}>Открыть договор <ArrowUpRight/></button></>}
function TransactionDetail({item,notify}){return <><p className="eyebrow">ДЕТАЛИ ОПЕРАЦИИ</p><h2>{item.title}</h2><div className="detail-pairs"><span>Статус<b className={item.status==='Исполнено'?'green':''}>{item.status}</b></span><span>Сумма<b>{item.amount}</b></span><span>Получатель / источник<b>{item.target}</b></span><span>Сеть<b>{item.network}</b></span><span>Идентификатор<b>{item.hash}</b><button onClick={()=>notify('Идентификатор скопирован')}><Copy size={14}/></button></span></div>{item.type==='blockchain'?<a className="chain-link" href="#" onClick={event=>{event.preventDefault();notify('Обозреватель сети будет подключён после интеграции')}}><ExternalLink/>Открыть в обозревателе сети</a>:<button className="chain-link" onClick={()=>notify('Выписка сформирована')}><Download/>Скачать выписку</button>}</>}
