// @ts-nocheck
import { useMemo, useState } from 'react'
import { ArrowUpRight, BarChart3, CalendarDays, Check, ChevronLeft, ChevronRight, CircleAlert, FileText, Landmark, ShieldCheck, UsersRound, WalletCards, X } from 'lucide-react'
import { useNavigate, useSearchParams } from 'react-router-dom'
import { Area, AreaChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './team-lead-reports.css'
import './team-lead-reports-v2.css'
import './team-lead-investor-document.css'
import './team-lead-reports-charts.css'
import './team-lead-reports-period.css'
import './team-lead-reports-period-picker.css'

type Report = { id: string; uid: string; investor: string; strategy: string; team: string; period: string; contract: string; capital: string; balance: string; result: string; total: string; withdrawn: string; reinvested: string; escrow: string; status: string; tone: string }

const reports: Report[] = [
  { id: 'r1', uid: 'UID477497399', investor: 'Павел Орлов', strategy: 'Orion Capital Strategy', team: 'Trading Team A', period: 'Август 2026', contract: 'BRK-OR-2026-014', capital: '60 250 USDT', balance: '63 142 USDT', result: '+2 892 USDT', total: '+10 250 USDT', withdrawn: '0 USDT', reinvested: '2 892 USDT', escrow: '7 500 USDT · 164%', status: 'Сформирован автоматически', tone: 'violet' },
  { id: 'r2', uid: 'UID118402577', investor: 'Анна Соколова', strategy: 'Orion Capital Strategy', team: 'Trading Team A', period: 'Август 2026', contract: 'BRK-OR-2026-018', capital: '25 000 USDT', balance: '26 200 USDT', result: '+1 200 USDT', total: '+1 500 USDT', withdrawn: '1 200 USDT', reinvested: '0 USDT', escrow: '3 100 USDT · 164%', status: 'Сформирован автоматически', tone: 'blue' },
  { id: 'r3', uid: 'UID930182641', investor: 'Мария Белова', strategy: 'Alpha Quant Strategy', team: 'Scalping Team B', period: 'Август 2026', contract: 'BRK-AQ-2026-009', capital: '28 900 USDT', balance: '29 990 USDT', result: '+1 090 USDT', total: '+4 900 USDT', withdrawn: '—', reinvested: '—', escrow: '3 000 USDT · 146%', status: 'Ожидается решение инвестора', tone: 'cyan' },
  { id: 'r4', uid: 'UID582104763', investor: 'Иван Лебедев', strategy: 'Orion Capital Strategy', team: 'Trading Team A', period: 'Август 2026', contract: 'BRK-OR-2026-019', capital: '12 000 USDT', balance: '12 576 USDT', result: '+576 USDT', total: '+720 USDT', withdrawn: '—', reinvested: '576 USDT', escrow: '1 400 USDT · 164%', status: 'Ожидается подпись соглашения', tone: 'amber' },
]
const reportPeriods = ['Август 2026', 'Июль 2026', 'II квартал 2026', '2026 год']

export function TeamLeadReports() {
  const navigate = useNavigate()
  const [params] = useSearchParams()
  const [mode, setMode] = useState<'investors' | 'company'>('investors')
  const [period, setPeriod] = useState('Август 2026')
  const [selected, setSelected] = useState<Report | null>(null)
  const investor = params.get('investor') ?? ''
  const strategy = params.get('strategy') ?? ''
  const visible = useMemo(() => reports.filter(item => (!investor || item.investor === investor) && (!strategy || item.strategy === strategy)).map(item => ({ ...item, period })), [investor, strategy, period])

  return <main className="tl-reports reports-v2">
    <header className="reports-head"><div><p>ОТЧЁТНОСТЬ</p><h2>Результаты и контроль</h2><span>Broker формирует инвесторские отчёты автоматически. Здесь — результат, обязательства и риски компании.</span></div><select value={period} onChange={event => setPeriod(event.target.value)}><option>Август 2026</option><option>Июль 2026</option><option>II квартал 2026</option><option>2026 год</option></select></header>
    <ReportPeriodPicker period={period} onChange={setPeriod} />
    <nav className="reports-tabs"><button className={mode === 'investors' ? 'active' : ''} onClick={() => setMode('investors')}><FileText size={15} /> Инвесторам</button><button className={mode === 'company' ? 'active' : ''} onClick={() => setMode('company')}><BarChart3 size={15} /> Компании</button></nav>
    {mode === 'investors' ? <InvestorReports reports={visible} filtered={Boolean(investor || strategy)} onOpen={setSelected} /> : <CompanyReport period={period} onSettlements={() => navigate('/team-lead/settlements')} onOpenInvestor={() => { setMode('investors'); setSelected(reports[0]) }} />}
    {selected && <InvestorReport report={selected} close={() => setSelected(null)} onSettlements={() => navigate('/team-lead/settlements')} />}
  </main>
}

function ReportPeriodPicker({ period, onChange }: { period: string; onChange: (value: string) => void }) {
  const months = ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь']
  const [open, setOpen] = useState(false)
  const currentYear = Number(period.match(/20\d{2}/)?.[0] ?? 2026)
  const [year, setYear] = useState(currentYear)
  const pickMonth = (month: string) => { onChange(`${month} ${year}`); setOpen(false) }
  const pickRange = (label: string) => { onChange(label); setOpen(false) }
  return <section className="reports-period-picker"><span>ПЕРИОД ОТЧЁТНОСТИ</span><div className="reports-period-picker__wrap"><button className="reports-period-trigger" onClick={() => setOpen(value => !value)}><CalendarDays size={14}/><strong>{period}</strong><ChevronRight size={15} className={open ? 'is-open' : ''}/></button>{open && <div className="reports-period-popover"><header><button onClick={() => setYear(value => value - 1)} aria-label="Предыдущий год"><ChevronLeft size={15}/></button><b>{year}</b><button onClick={() => setYear(value => value + 1)} aria-label="Следующий год"><ChevronRight size={15}/></button></header><div className="report-month-grid">{months.map(month => <button key={month} className={period === `${month} ${year}` ? 'active' : ''} onClick={() => pickMonth(month)}>{month.slice(0, 3)}</button>)}</div><footer><button onClick={() => pickRange(`I квартал ${year}`)}>I квартал</button><button onClick={() => pickRange(`II квартал ${year}`)}>II квартал</button><button onClick={() => pickRange(`III квартал ${year}`)}>III квартал</button><button onClick={() => pickRange(`IV квартал ${year}`)}>IV квартал</button><button onClick={() => pickRange(`${year} год`)}>Весь год</button></footer></div>}</div><small>Нажмите на период, чтобы выбрать месяц, квартал или год</small></section>
}

function PeriodNavigator({ period, onChange }: { period: string; onChange: (value: string) => void }) {
  const index = Math.max(0, reportPeriods.indexOf(period))
  const prev = () => onChange(reportPeriods[(index + reportPeriods.length - 1) % reportPeriods.length])
  const next = () => onChange(reportPeriods[(index + 1) % reportPeriods.length])
  return <section className="reports-period-nav"><span>ПЕРИОД ОТЧЁТНОСТИ</span><div><button onClick={prev} aria-label="Предыдущий период"><ChevronLeft size={16}/></button><strong><CalendarDays size={14}/>{period}</strong><button onClick={next} aria-label="Следующий период"><ChevronRight size={16}/></button></div><small>{index === 0 ? 'Ежемесячный отчёт' : index === 2 ? 'Квартальный отчёт' : index === 3 ? 'Годовой отчёт' : 'Архивный ежемесячный отчёт'}</small></section>
}

function InvestorReports({ reports, filtered, onOpen }: { reports: Report[]; filtered: boolean; onOpen: (report: Report) => void }) {
  return <section className="investor-reports"><header><div><p>АВТОМАТИЧЕСКИЕ ОТЧЁТЫ ИНВЕСТОРОВ</p><h3>{filtered ? 'Отчёты по выбранной инвестиции' : 'Все сформированные отчёты'}</h3></div><span>{reports.length} документа</span></header><div className="investor-report-list">{reports.map(report => <article className={report.tone} key={report.id}><div className="report-person"><i>{report.investor.split(' ').map(part => part[0]).join('')}</i><span><b>{report.investor}</b><small>{report.contract} · {report.period}</small></span></div><div><span>Стратегия</span><b>{report.strategy}</b><small>{report.team}</small></div><div><span>Капитал</span><b>{report.capital}</b></div><div><span>Результат периода</span><b className="green">{report.result}</b></div><div><span>Статус</span><b>{report.status}</b></div><button onClick={() => onOpen(report)} aria-label="Открыть отчёт"><ArrowUpRight size={17} /></button></article>)}</div></section>
}

function CompanyReport({ period, onSettlements, onOpenInvestor }: { period: string; onSettlements: () => void; onOpenInvestor: () => void }) {
  const teams = [{ name: 'Trading Team A', value: 97250, company: 1167, tone: 'violet' }, { name: 'Scalping Team B', value: 28900, company: 239, tone: 'blue' }, { name: 'Arbitrage Team C', value: 18750, company: 48, tone: 'amber' }]
  const total = teams.reduce((sum, item) => sum + item.value, 0)
  return <section className="company-report">
    <div className="company-kpis"><Metric title="Доход компании" value="1 454 USDT" note={`за ${period}`} tone="green" /><Metric title="Ожидает исполнения" value="1 666 USDT" note="решение инвестора / подпись" tone="violet" /><Metric title="Капитал под управлением" value="144 900 USDT" note="4 активных договора" /><Metric title="Исполнение обязательств" value="92%" note="11 из 12 условий выполнены" tone="blue" /></div>
    <CompanyAnalyticsV2 />
    <div className="company-main-grid"><section className="company-income"><header><div><p>ДОХОДЫ И РАСПРЕДЕЛЕНИЯ</p><h3>Доход компании</h3></div><span>{period}</span></header><div className="income-chart"><i style={{ height: '52%' }} /><i style={{ height: '71%' }} /><i style={{ height: '63%' }} /><i style={{ height: '86%' }} /><i style={{ height: '76%' }} /><i className="accent" style={{ height: '94%' }} /></div><div className="income-summary"><span><b>2 300 USDT</b> начислено</span><span><b>846 USDT</b> распределено</span><span><b>1 454 USDT</b> остаётся компании</span></div></section><section className="company-obligations"><header><p>ИСПОЛНЕНИЕ ОБЯЗАТЕЛЬСТВ</p><h3>Требуют контроля</h3></header><Obligation icon={<Check size={15} />} tone="green" title="9 договоров" text="исполняются по стандартному сценарию" onClick={onSettlements} /><Obligation icon={<CircleAlert size={15} />} tone="amber" title="2 решения инвесторов" text="ожидают вывод или реинвестирование" onClick={onSettlements} /><Obligation icon={<CircleAlert size={15} />} tone="red" title="1 исключение" text="недостаточное покрытие escrow" onClick={onSettlements} /></section></div>
    <section className="company-allocation"><header><div><p>КОНЦЕНТРАЦИЯ И РИСКИ</p><h3>Распределение капитала по командам</h3></div><span>Контроль включается при высокой концентрации на одной команде</span></header>{teams.map(item => <article key={item.name}><div><b>{item.name}</b><small>{item.value.toLocaleString('ru-RU')} USDT · доход компании {item.company.toLocaleString('ru-RU')} USDT</small></div><div className="allocation-bar"><i className={item.tone} style={{ width: `${Math.round(item.value / total * 100)}%` }} /></div><strong>{Math.round(item.value / total * 100)}%</strong></article>)}<footer><ShieldCheck size={16} /> Trading Team A: 67% капитала — выше порога 65%. Стоит рассмотреть диверсификацию.</footer></section>
    <section className="company-infrastructure"><header><div><p>ИНФРАСТРУКТУРА КАПИТАЛА</p><h3>Счета и API</h3></div><button onClick={onSettlements}>Открыть расчёты <ArrowUpRight size={14} /></button></header><div><span><Landmark size={16} /><b>11 subaccounts</b><small>9 подключено · 2 требуют настройки</small></span><span><WalletCards size={16} /><b>6 430 USDT на main accounts</b><small>доступно для распределения</small></span><button onClick={onOpenInvestor}><UsersRound size={16} /> Открыть инвесторскую отчётность</button></div></section>
  </section>
}

function CompanyAnalytics() {
  const [period, setPeriod] = useState<'30д' | '90д' | 'год'>('90д')
  const [mode, setMode] = useState<'capital' | 'teams' | 'sources'>('capital')
  const series = period === '30д'
    ? [{ label: '1 авг', capital: 128400, trading: 78400, escrow: 12000, wallets: 3800 }, { label: '7 авг', capital: 132100, trading: 80500, escrow: 12500, wallets: 4100 }, { label: '14 авг', capital: 136800, trading: 84300, escrow: 12500, wallets: 5100 }, { label: '21 авг', capital: 141700, trading: 88700, escrow: 13200, wallets: 5900 }, { label: '31 авг', capital: 144900, trading: 91000, escrow: 14000, wallets: 6400 }]
    : period === '90д'
      ? [{ label: 'июн', capital: 110000, trading: 69000, escrow: 9200, wallets: 2800, teamA: 57000, teamB: 21000, teamC: 12000 }, { label: 'июл', capital: 121400, trading: 74800, escrow: 10500, wallets: 3500, teamA: 65000, teamB: 23500, teamC: 13800 }, { label: 'авг', capital: 128400, trading: 78400, escrow: 12000, wallets: 3800, teamA: 71000, teamB: 26000, teamC: 15000 }, { label: 'сент', capital: 136800, trading: 84300, escrow: 12500, wallets: 5100, teamA: 81200, teamB: 28500, teamC: 16600 }, { label: 'окт', capital: 141700, trading: 88700, escrow: 13200, wallets: 5900, teamA: 90700, teamB: 29200, teamC: 17800 }, { label: 'ноя', capital: 144900, trading: 91000, escrow: 14000, wallets: 6400, teamA: 97250, teamB: 28900, teamC: 18750 }]
      : [{ label: 'янв', capital: 83000, trading: 51000, escrow: 7000, wallets: 2000, teamA: 43000, teamB: 18000, teamC: 9000 }, { label: 'мар', capital: 97000, trading: 61000, escrow: 8200, wallets: 2500, teamA: 52000, teamB: 20000, teamC: 11000 }, { label: 'май', capital: 106000, trading: 66500, escrow: 9000, wallets: 3000, teamA: 56000, teamB: 22000, teamC: 13000 }, { label: 'июл', capital: 121400, trading: 74800, escrow: 10500, wallets: 3500, teamA: 65000, teamB: 23500, teamC: 13800 }, { label: 'сен', capital: 136800, trading: 84300, escrow: 12500, wallets: 5100, teamA: 81200, teamB: 28500, teamC: 16600 }, { label: 'ноя', capital: 144900, trading: 91000, escrow: 14000, wallets: 6400, teamA: 97250, teamB: 28900, teamC: 18750 }]
  const lines = mode === 'capital' ? [{ dataKey: 'capital', name: 'Общий капитал', color: '#bd72ff' }] : mode === 'teams' ? [{ dataKey: 'teamA', name: 'Trading Team A', color: '#b866ff' }, { dataKey: 'teamB', name: 'Scalping Team B', color: '#50a3ff' }, { dataKey: 'teamC', name: 'Arbitrage Team C', color: '#ffbf45' }] : [{ dataKey: 'trading', name: 'В торговле', color: '#b866ff' }, { dataKey: 'escrow', name: 'Escrow', color: '#54e76d' }, { dataKey: 'wallets', name: 'Свободные кошельки', color: '#50a3ff' }]
  return <section className="company-analytics"><header><div><p>ДИНАМИКА КАПИТАЛА</p><h3>{mode === 'capital' ? 'Капитал под управлением' : mode === 'teams' ? 'Распределение по торговым командам' : 'Где находятся средства'}</h3></div><div className="analytics-controls"><div>{(['capital', 'teams', 'sources'] as const).map(item => <button key={item} className={mode === item ? 'active' : ''} onClick={() => setMode(item)}>{item === 'capital' ? 'Общий' : item === 'teams' ? 'Команды' : 'Источники'}</button>)}</div><div>{(['30д', '90д', 'год'] as const).map(item => <button key={item} className={period === item ? 'active' : ''} onClick={() => setPeriod(item)}>{item}</button>)}</div></div></header><div className="company-chart"><ResponsiveContainer width="100%" height={245} minWidth={0}><AreaChart data={series} margin={{ top: 14, right: 8, left: -18, bottom: 0 }}><defs>{lines.map(line => <linearGradient key={line.dataKey} id={`fill-${line.dataKey}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={line.color} stopOpacity={.3}/><stop offset="100%" stopColor={line.color} stopOpacity={0}/></linearGradient>)}</defs><CartesianGrid vertical={false} stroke="rgba(173,124,255,.12)" strokeDasharray="3 5"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#8392aa', fontSize: 10 }}/><YAxis tickLine={false} axisLine={false} tick={{ fill: '#8392aa', fontSize: 10 }} tickFormatter={value => `${Math.round(value / 1000)}k`}/><Tooltip contentStyle={{ background: '#0b1430', border: '1px solid rgba(180,110,255,.45)', borderRadius: 12, fontSize: 11 }} formatter={(value: number) => `${value.toLocaleString('ru-RU')} USDT`}/><Legend wrapperStyle={{ fontSize: 11, paddingTop: 9 }}/>{lines.map(line => <Area key={line.dataKey} type="monotone" dataKey={line.dataKey} name={line.name} stroke={line.color} strokeWidth={2.4} fill={`url(#fill-${line.dataKey})`} dot={false} activeDot={{ r: 4, fill: line.color }}/>)}</AreaChart></ResponsiveContainer></div></section>
}

function Metric({ title, value, note, tone = '' }: { title: string; value: string; note: string; tone?: string }) { return <article className={tone}><span>{title}</span><b>{value}</b><small>{note}</small></article> }
function Obligation({ icon, tone, title, text, onClick }: { icon: React.ReactNode; tone: string; title: string; text: string; onClick: () => void }) { return <button onClick={onClick}><i className={tone}>{icon}</i><span><b>{title}</b><small>{text}</small></span><ArrowUpRight size={14} /></button> }

function InvestorReport({ report, close, onSettlements }: { report: Report; close: () => void; onSettlements: () => void }) {
  return <div className="investor-report-modal"><button className="report-backdrop" onClick={close} /><section className="investor-report-document"><button className="report-close" onClick={close}><X /></button><header><p>АВТОМАТИЧЕСКИЙ ОТЧЁТ ИНВЕСТОРА</p><h3>{report.strategy}</h3><span>{report.team} · сформирован Broker</span></header><div className="report-document-top"><div><span>ДОГОВОР №</span><b>{report.contract}</b></div><div><span>ОТЧЁТНЫЙ ПЕРИОД</span><b>01.08.2026 — 31.08.2026</b></div></div><div className="report-document-hero"><div><p>{report.uid}</p><b>{report.investor}</b><span>Investor · Trigonum ID</span></div><div><p>БАЛАНС НА 31.08.2026</p><strong>{report.balance}</strong><span>Инвестиция: {report.capital}</span></div></div><div className="report-kpis report-kpis--document"><span>Результат за август<b className="green">{report.result}</b></span><span>Прибыль с начала инвестирования<b>{report.total}</b></span><span>Выплачено инвестору<b>{report.withdrawn}</b></span><span>Реинвестировано<b>{report.reinvested}</b></span></div><InvestorResultChart report={report} /><div className="report-document-grid"><article><p>ДВИЖЕНИЕ СРЕДСТВ</p><div><span>Стартовый баланс</span><b>{report.capital}</b></div><div><span>Прибыль инвестора</span><b className="green">{report.result}</b></div><div><span>Остаток к выплате</span><b>{report.withdrawn === '0 USDT' ? report.result : '0 USDT'}</b></div></article><article><p>ДОГОВОР И РАЗМЕЩЕНИЕ</p><div><span>Следующий отчёт</span><b>01 сентября 2026</b></div><div><span>Торговая команда</span><b>{report.team}</b></div><div><span>Escrow</span><b>{report.escrow}</b></div></article></div><div className="report-document-note"><FileText size={17} /><span>Отчёт фиксирует результат на дату формирования. Вывод или реинвестирование выполняются после решения инвестора и условий договора.</span></div><footer><button onClick={onSettlements}>Открыть расчёт и решение <ArrowUpRight size={15} /></button><button onClick={close}>Закрыть</button></footer></section></div>
}

function InvestorResultChartOld({ report }: { report: Report }) {
  const [range, setRange] = useState<'месяц' | 'квартал' | 'год'>('год')
  const data = range === 'месяц' ? [{ label: '01', value: 60250 }, { label: '07', value: 60600 }, { label: '14', value: 61180 }, { label: '21', value: 61850 }, { label: '31', value: 63142 }] : range === 'квартал' ? [{ label: 'июн', value: 56100 }, { label: 'июл', value: 58400 }, { label: 'авг', value: 60250 }, { label: 'сен', value: 61500 }, { label: 'окт', value: 63142 }] : [{ label: 'янв', value: 52000 }, { label: 'мар', value: 54500 }, { label: 'май', value: 56200 }, { label: 'июл', value: 58500 }, { label: 'сен', value: 60600 }, { label: 'ноя', value: 63142 }]
  return <section className="investor-result-chart"><header><div><p>ДИНАМИКА БАЛАНСА</p><b>{report.result} <small>за выбранный период</small></b></div><div>{(['месяц', 'квартал', 'год'] as const).map(item => <button key={item} className={range === item ? 'active' : ''} onClick={() => setRange(item)}>{item}</button>)}</div></header><ResponsiveContainer width="100%" height={176} minWidth={0}><AreaChart data={data} margin={{ top: 12, right: 10, left: -18, bottom: 0 }}><defs><linearGradient id="investor-balance" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#be70ff" stopOpacity=".36"/><stop offset="100%" stopColor="#be70ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(190,112,255,.14)" strokeDasharray="3 5"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#8795ad', fontSize: 10 }}/><YAxis hide domain={['dataMin - 500', 'dataMax + 500']}/><Tooltip contentStyle={{ background: '#0b1430', border: '1px solid rgba(190,112,255,.5)', borderRadius: 10, fontSize: 11 }} formatter={(value: number) => `${value.toLocaleString('ru-RU')} USDT`}/><Area type="monotone" dataKey="value" stroke="#c176ff" strokeWidth={2.4} fill="url(#investor-balance)" dot={false} activeDot={{ r: 4, fill: '#e4c4ff' }}/></AreaChart></ResponsiveContainer></section>
}

function CompanyAnalyticsV2() {
  const [period, setPeriod] = useState<'month' | 'quarter' | 'year'>('quarter')
  const data = period === 'month'
    ? [{ label: '1 авг', invested: 128400, investorProfit: 8920, companyProfit: 1120 }, { label: '8 авг', invested: 132100, investorProfit: 9410, companyProfit: 1190 }, { label: '15 авг', invested: 136800, investorProfit: 10280, companyProfit: 1285 }, { label: '22 авг', invested: 141700, investorProfit: 11060, companyProfit: 1370 }, { label: '31 авг', invested: 144900, investorProfit: 11710, companyProfit: 1454 }]
    : period === 'quarter'
      ? [{ label: 'I кв.', invested: 83000, investorProfit: 4100, companyProfit: 520 }, { label: 'II кв.', invested: 106000, investorProfit: 6750, companyProfit: 840 }, { label: 'III кв.', invested: 128400, investorProfit: 8920, companyProfit: 1120 }, { label: 'IV кв.', invested: 144900, investorProfit: 11710, companyProfit: 1454 }]
      : [{ label: '2023', invested: 55000, investorProfit: 2200, companyProfit: 310 }, { label: '2024', invested: 76000, investorProfit: 4950, companyProfit: 640 }, { label: '2025', invested: 108000, investorProfit: 8360, companyProfit: 1060 }, { label: '2026', invested: 144900, investorProfit: 11710, companyProfit: 1454 }]
  return <section className="company-analytics company-analytics--finance"><header><div><p>ФИНАНСОВАЯ ДИНАМИКА</p><h3>Вложения и результат по периодам</h3><span>Капитал и накопленные результаты по всем действующим договорам</span></div><div className="period-switcher">{([['month', 'Месяц'], ['quarter', 'Квартал'], ['year', 'Год']] as const).map(([id, label]) => <button key={id} className={period === id ? 'active' : ''} onClick={() => setPeriod(id)}>{label}</button>)}</div></header><div className="financial-legend"><span><i className="invested" />Вложенные средства</span><span><i className="investor" />Прибыль инвесторов</span><span><i className="company" />Доход компании</span></div><div className="company-chart"><ResponsiveContainer width="100%" height={255} minWidth={0}><AreaChart data={data} margin={{ top: 18, right: 8, left: -12, bottom: 0 }}><defs><linearGradient id="invested-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b866ff" stopOpacity=".26"/><stop offset="1" stopColor="#b866ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(173,124,255,.12)" strokeDasharray="3 5"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#8392aa', fontSize: 10 }}/><YAxis yAxisId="capital" tickLine={false} axisLine={false} tick={{ fill: '#8392aa', fontSize: 10 }} tickFormatter={value => `${Math.round(value / 1000)}k`}/><YAxis yAxisId="profit" orientation="right" tickLine={false} axisLine={false} tick={{ fill: '#8392aa', fontSize: 10 }} tickFormatter={value => `${Math.round(value / 1000)}k`}/><Tooltip contentStyle={{ background: '#0b1430', border: '1px solid rgba(180,110,255,.45)', borderRadius: 12, fontSize: 11 }}/><Area yAxisId="capital" type="monotone" dataKey="invested" name="Вложенные средства" stroke="#b866ff" strokeWidth={2.5} fill="url(#invested-fill)" dot={false} activeDot={{ r: 4 }}/><Area yAxisId="profit" type="monotone" dataKey="investorProfit" name="Прибыль инвесторов" stroke="#50a3ff" strokeWidth={2.2} fill="none" dot={false} activeDot={{ r: 4 }}/><Area yAxisId="profit" type="monotone" dataKey="companyProfit" name="Доход компании" stroke="#55e866" strokeWidth={2.2} fill="none" dot={false} activeDot={{ r: 4 }}/></AreaChart></ResponsiveContainer></div></section>
}

function InvestorResultChart({ report }: { report: Report }) {
  const [period, setPeriod] = useState<'month' | 'quarter' | 'year'>('quarter')
  const data = period === 'month'
    ? [{ label: '1 авг', invested: 60250, investorProfit: 8600, companyProfit: 1050 }, { label: '8 авг', invested: 60250, investorProfit: 9050, companyProfit: 1100 }, { label: '15 авг', invested: 60250, investorProfit: 9700, companyProfit: 1180 }, { label: '22 авг', invested: 60250, investorProfit: 10320, companyProfit: 1240 }, { label: '31 авг', invested: 60250, investorProfit: 10950, companyProfit: 1320 }]
    : period === 'quarter'
      ? [{ label: 'I кв.', invested: 50000, investorProfit: 2900, companyProfit: 390 }, { label: 'II кв.', invested: 54000, investorProfit: 5100, companyProfit: 660 }, { label: 'III кв.', invested: 57500, investorProfit: 7850, companyProfit: 950 }, { label: 'IV кв.', invested: 60250, investorProfit: 10950, companyProfit: 1320 }]
      : [{ label: '2023', invested: 38000, investorProfit: 1200, companyProfit: 160 }, { label: '2024', invested: 45000, investorProfit: 3500, companyProfit: 440 }, { label: '2025', invested: 52500, investorProfit: 7150, companyProfit: 880 }, { label: '2026', invested: 60250, investorProfit: 10950, companyProfit: 1320 }]
  return <section className="investor-result-chart investor-result-chart--finance"><header><div><p>ДИНАМИКА ИНВЕСТИЦИИ</p><b>Капитал, прибыль инвестора и доход компании</b></div><div className="period-switcher">{([['month', 'Месяц'], ['quarter', 'Квартал'], ['year', 'Год']] as const).map(([id, label]) => <button key={id} className={period === id ? 'active' : ''} onClick={() => setPeriod(id)}>{label}</button>)}</div></header><div className="financial-legend"><span><i className="invested" />Вложено</span><span><i className="investor" />Инвестор</span><span><i className="company" />Компания</span></div><ResponsiveContainer width="100%" height={192} minWidth={0}><AreaChart data={data} margin={{ top: 12, right: 5, left: -14, bottom: 0 }}><defs><linearGradient id="single-invested" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#b866ff" stopOpacity=".25"/><stop offset="1" stopColor="#b866ff" stopOpacity="0"/></linearGradient></defs><CartesianGrid vertical={false} stroke="rgba(190,112,255,.13)" strokeDasharray="3 5"/><XAxis dataKey="label" tickLine={false} axisLine={false} tick={{ fill: '#8795ad', fontSize: 10 }}/><YAxis yAxisId="capital" hide/><YAxis yAxisId="profit" hide/><Tooltip contentStyle={{ background: '#0b1430', border: '1px solid rgba(190,112,255,.5)', borderRadius: 10, fontSize: 11 }}/><Area yAxisId="capital" type="monotone" dataKey="invested" name="Вложено" stroke="#b866ff" strokeWidth={2.3} fill="url(#single-invested)" dot={false}/><Area yAxisId="profit" type="monotone" dataKey="investorProfit" name="Инвестор" stroke="#50a3ff" strokeWidth={2.2} fill="none" dot={false}/><Area yAxisId="profit" type="monotone" dataKey="companyProfit" name="Компания" stroke="#55e866" strokeWidth={2.2} fill="none" dot={false}/></AreaChart></ResponsiveContainer></section>
}
