// @ts-nocheck
import { useMemo, useState } from 'react'
import { ArrowUpRight, Check, Clock3, FileText, Heart, Info, MessageCircle, Search, ShieldCheck, Users, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import './investor-offers.css'
import './offers-tooltips.css'

type Risk = 'Консервативный' | 'Сбалансированный' | 'Динамичный'
type Offer = {id:string;name:string;team:string;risk:Risk;yield:string;minimum:string;term:string;cover:string;investors:number;description:string;tags:string[];visual:string;withdrawal:string;fee:string}
const offers:Offer[]=[
  {id:'orion',name:'Orion Capital Strategy',team:'Orion Capital',risk:'Сбалансированный',yield:'+20,45%',minimum:'5 000',term:'12 месяцев',cover:'164%',investors:38,visual:'orion',description:'Системная стратегия с диверсификацией по ликвидным криптоактивам и контролем просадки.',tags:['Регулярная отчётность','Вывод раз в месяц'],withdrawal:'Раз в месяц',fee:'20% от прибыли'},
  {id:'alpha',name:'Alpha Quant Strategy',team:'Alpha Quant',risk:'Динамичный',yield:'+20,39%',minimum:'2 500',term:'6 месяцев',cover:'146%',investors:24,visual:'alpha',description:'Количественная стратегия на нескольких независимых торговых моделях.',tags:['Открыта для новых инвесторов','Вывод раз в квартал'],withdrawal:'Раз в квартал',fee:'18% от прибыли'},
  {id:'delta',name:'Delta Diversified Strategy',team:'Delta Partners',risk:'Консервативный',yield:'+14,17%',minimum:'10 000',term:'18 месяцев',cover:'178%',investors:16,visual:'delta',description:'Защитный портфель с ограниченным риском и приоритетом сохранения капитала.',tags:['Низкая волатильность','Вывод раз в месяц'],withdrawal:'Раз в месяц',fee:'15% от прибыли'},
  {id:'beta',name:'Beta Income Strategy',team:'Beta Income',risk:'Сбалансированный',yield:'+16,25%',minimum:'1 000',term:'3 месяца',cover:'151%',investors:51,visual:'beta',description:'Стратегия регулярного дохода с коротким инвестиционным горизонтом.',tags:['Короткий срок','Пополнение в любое время'],withdrawal:'По окончании периода',fee:'17% от прибыли'},
  {id:'nova',name:'Nova Trend Strategy',team:'Nova Systems',risk:'Динамичный',yield:'+28,80%',minimum:'7 500',term:'12 месяцев',cover:'139%',investors:12,visual:'nova',description:'Трендовая стратегия для инвестора, готового к более высокой волатильности.',tags:['Повышенный потенциал','Вывод раз в квартал'],withdrawal:'Раз в квартал',fee:'22% от прибыли'},
  {id:'arc',name:'Arc Stable Strategy',team:'Arc Capital',risk:'Консервативный',yield:'+11,62%',minimum:'3 000',term:'9 месяцев',cover:'183%',investors:29,visual:'arc',description:'Умеренная стратегия с ежедневным контролем залогового покрытия.',tags:['Приоритет сохранности','Ежемесячный отчёт'],withdrawal:'Раз в месяц',fee:'14% от прибыли'},
]
export function InvestorOffers(){const [query,setQuery]=useState(''),[risk,setRisk]=useState<Risk|'Все'>('Все'),[selected,setSelected]=useState<Offer|null>(null),[saved,setSaved]=useState<string[]>([]),[applied,setApplied]=useState<string[]>([]);const shown=useMemo(()=>offers.filter(item=>(risk==='Все'||item.risk===risk)&&`${item.name} ${item.team}`.toLowerCase().includes(query.toLowerCase())),[query,risk]);const navigate=useNavigate();const message=offer=>navigate(`/investor/messages?team=${encodeURIComponent(offer.team)}&offer=${encodeURIComponent(offer.name)}`);return <main className="market-page"><header className="market-heading"><div><p className="eyebrow">МАРКЕТ СТРАТЕГИЙ</p><h2>Найдите подходящую стратегию</h2><span>Условия, защита капитала и прямой контакт с тимлидом.</span></div><div className="market-note"><ShieldCheck/>Показатели не гарантируют будущую доходность</div></header><div className="market-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск стратегии или команды"/></label><div>{(['Все','Консервативный','Сбалансированный','Динамичный'] as const).map(item=><button key={item} className={risk===item?'active':''} onClick={()=>setRisk(item)}>{item}</button>)}</div><span>{shown.length} стратегий</span></div><section className="market-grid">{shown.map(offer=><OfferCard key={offer.id} offer={offer} saved={saved.includes(offer.id)} applied={applied.includes(offer.id)} save={()=>setSaved(items=>items.includes(offer.id)?items.filter(id=>id!==offer.id):[...items,offer.id])} open={()=>setSelected(offer)}/>)}</section>{selected&&<OfferModal offer={selected} saved={saved.includes(selected.id)} applied={applied.includes(selected.id)} close={()=>setSelected(null)} message={()=>message(selected)} apply={()=>setApplied(items=>items.includes(selected.id)?items:[...items,selected.id])}/>}</main>}
function OfferCard({offer,saved,applied,save,open}:{offer:Offer;saved:boolean;applied:boolean;save:()=>void;open:()=>void}){return <article className="market-card"><div className={`market-cover ${offer.visual}`}><div className="cover-grid"/><span>{offer.team}</span><button aria-label="В избранное" className={saved?'saved':''} onClick={save}><Heart fill={saved?'currentColor':'none'}/></button><div className="cover-graph"/></div><div className="market-card-body"><div className="card-title"><div><p>{offer.risk}</p><h3>{offer.name}</h3></div></div><p className="card-description">{offer.description}</p><div className="card-terms"><div><span>Доходность</span><b>{offer.yield}</b></div><div><span>Минимум</span><b>{offer.minimum}<small> USDT</small></b></div><div><span>Срок</span><b>{offer.term}</b></div></div><div className="card-footer"><span><Users/> {offer.investors} инвесторов</span><button className={applied?'applied':''} onClick={open}>{applied?<><Check/>Заявка отправлена</>:<>Подробнее<ArrowUpRight/></>}</button></div></div></article>}
function OfferModal({offer,applied,close,message,apply}:{offer:Offer;applied:boolean;close:()=>void;message:()=>void;apply:()=>void}){const [document,setDocument]=useState(false);return <div className="market-modal"><button className="modal-backdrop" onClick={close}/><section><button className="modal-close" onClick={close}><X/></button><div className={`modal-cover ${offer.visual}`}><span>{offer.team}</span><div className="cover-graph"/></div><div className="modal-content">{document?<><p className="eyebrow">УСЛОВИЯ И ДОГОВОР</p><h2>Договор {offer.name}</h2><div className="conditions"><span>Срок участия <b>{offer.term}</b></span><span>Минимальная сумма <b>{offer.minimum} USDT</b></span><span>Порядок вывода <b>{offer.withdrawal}</b></span><span>Комиссия тимлида <b>{offer.fee}</b></span><span>Расчётный период <b>Ежемесячно</b></span></div><button className="offer-document" onClick={()=>setDocument(false)}>← К описанию стратегии</button></>:<><p className="eyebrow">ИНВЕСТИЦИОННОЕ ПРЕДЛОЖЕНИЕ</p><h2>{offer.name}</h2><p className="modal-description">{offer.description}</p><div className="modal-highlights"><div><b>{offer.yield}</b><span>доходность за 12 месяцев</span></div><div className="coverage-tip"><b>{offer.cover}</b><span>покрытие escrow <Info/></span><aside>Это отношение залога на escrow-счёте к начисленной комиссии. При значении от 100% комиссия обеспечена: залог нельзя свободно вывести до завершения расчёта.</aside></div><div><b>{offer.investors}</b><span>активных инвесторов</span></div></div><div className="conditions"><p>ОСНОВНЫЕ УСЛОВИЯ</p><span>Минимальная сумма <b>{offer.minimum} USDT</b></span><span>Срок участия <b>{offer.term}</b></span><span>Вывод средств <b>{offer.withdrawal}</b></span><span>Комиссия тимлида <b>{offer.fee}</b></span></div><div className="modal-tags">{offer.tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className="offer-document" onClick={()=>setDocument(true)}><FileText/>Просмотреть условия и договор<ArrowUpRight/></button></>}<div className="modal-actions"><button className="write-lead" onClick={message}><MessageCircle/>Написать тимлиду</button><button className="market-apply" disabled={applied} onClick={apply}>{applied?<><Check/>Заявка отправлена</>:'Подать заявку'}</button></div><p className="modal-foot"><Clock3/>Заявка рассматривается тимлидом в течение рабочего дня.</p></div></section></div>}
