// @ts-nocheck
import { useEffect, useMemo, useState } from 'react'
import { ArrowUpRight, Check, Clock3, FileText, Heart, Info, MessageCircle, Search, ShieldCheck, Users, WalletCards, X } from 'lucide-react'
import { useNavigate } from 'react-router-dom'
import { readOfferApplications, saveOfferApplications, offerApplicationsEvent } from '../../shared/offer-applications'
import type { OfferApplication } from '../../shared/offer-applications'
import './investor-offers.css'
import './offers-tooltips.css'

type Risk = 'Консервативный' | 'Сбалансированный' | 'Динамичный'
type Offer = {id:string;name:string;team:string;risk:Risk;yield:string;minimum:string;term:string;cover:string;investors:number;description:string;tags:string[];visual:string;withdrawal:string;fee:string}
const offers:Offer[]=[
  {id:'orion',name:'Orion Capital Strategy',team:'Orion Capital',risk:'Сбалансированный',yield:'+20,45%',minimum:'5 000',term:'12 месяцев',cover:'164%',investors:38,visual:'orion',description:'Системная стратегия с диверсификацией по ликвидным криптоактивам и контролем просадки.',tags:['Регулярная отчётность','Вывод раз в месяц'],withdrawal:'Раз в месяц',fee:'20% от прибыли'},
  {id:'alpha',name:'Alpha Quant Strategy',team:'Alpha Quant',risk:'Динамичный',yield:'+20,39%',minimum:'2 500',term:'6 месяцев',cover:'146%',investors:24,visual:'alpha',description:'Количественная стратегия на нескольких независимых торговых моделях.',tags:['Открыта для новых инвесторов','Вывод раз в квартал'],withdrawal:'Раз в квартал',fee:'18% от прибыли'},
  {id:'delta',name:'Delta Diversified Strategy',team:'Delta Partners',risk:'Консервативный',yield:'+14,17%',minimum:'10 000',term:'18 месяцев',cover:'178%',investors:16,visual:'delta',description:'Защитный портфель с ограниченным риском и приоритетом сохранения капитала.',tags:['Низкая волатильность','Вывод раз в месяц'],withdrawal:'Раз в месяц',fee:'15% от прибыли'},
  {id:'beta',name:'Beta Income Strategy',team:'Beta Income',risk:'Сбалансированный',yield:'+16,25%',minimum:'1 000',term:'3 месяца',cover:'151%',investors:51,visual:'beta',description:'Стратегия регулярного дохода с коротким инвестиционным горизонтом.',tags:['Короткий срок','Пополнение в любое время'],withdrawal:'По окончании периода',fee:'17% от прибыли'},
  {id:'nova',name:'Nova Trend Strategy',team:'Nova Systems',risk:'Динамичный',yield:'+28,80%',minimum:'7 500',term:'12 месяцев',cover:'139%',investors:12,visual:'nova',description:'Трендовая стратегия для инвестора, готового к более высокой волатильности.',tags:['Повышенный потенциал','Вывод раз в квартал'],withdrawal:'Раз в квартал',fee:'22% от прибыли'},
  {id:'arc',name:'Arc Stable Strategy',team:'Arc Capital',risk:'Консервативный',yield:'+11,62%',minimum:'3 000',term:'9 месяцев',cover:'183%',investors:29,visual:'arc',description:'Умеренная стратегия с ежедневным контролем залогового покрытия.',tags:['Приоритет сохранности','Ежемесячный отчёт'],withdrawal:'Раз в месяц',fee:'14% от прибыли'},
]
const statusText = { review:'На рассмотрении', clarification:'Нужны уточнения', contract_ready:'Договор готов', funding:'Ожидает пополнения', declined:'Заявка отклонена' }
const toAmount=(value:string)=>Number(value.replace(/\s/g,''))||0

export function InvestorOffers(){
  const [query,setQuery]=useState(''),[risk,setRisk]=useState<Risk|'Все'>('Все'),[selected,setSelected]=useState<Offer|null>(null),[saved,setSaved]=useState<string[]>([]),[applications,setApplications]=useState<OfferApplication[]>(readOfferApplications()),[applying,setApplying]=useState<Offer|null>(null)
  useEffect(()=>{const refresh=()=>setApplications(readOfferApplications());window.addEventListener(offerApplicationsEvent,refresh);return()=>window.removeEventListener(offerApplicationsEvent,refresh)},[])
  const shown=useMemo(()=>offers.filter(item=>(risk==='Все'||item.risk===risk)&&`${item.name} ${item.team}`.toLowerCase().includes(query.toLowerCase())),[query,risk]); const navigate=useNavigate(); const message=(offer:Offer)=>navigate(`/investor/messages?team=${encodeURIComponent(offer.team)}&offer=${encodeURIComponent(offer.name)}`); const applicationFor=(offer:Offer)=>applications.find(application=>application.offerId===offer.id&&application.status!=='declined')
  return <main className="market-page"><header className="market-heading"><div><p className="eyebrow">МАРКЕТ СТРАТЕГИЙ</p><h2>Найдите подходящую стратегию</h2><span>Условия, защита капитала и прямой контакт с тимлидом.</span></div><div className="market-note"><ShieldCheck/>Показатели не гарантируют будущую доходность</div></header>
    {applications.length>0&&<section className="market-applications"><div><p>МОИ ЗАЯВКИ</p><b>{applications.filter(item=>item.status!=='declined').length} в работе</b></div>{applications.slice(0,3).map(item=><button key={item.id} onClick={()=>{const offer=offers.find(current=>current.id===item.offerId);if(offer)setSelected(offer)}}><span>{item.offerName}</span><em className={item.status}>{statusText[item.status]}</em><ArrowUpRight size={15}/></button>)}</section>}
    <div className="market-toolbar"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Поиск стратегии или команды"/></label><div>{(['Все','Консервативный','Сбалансированный','Динамичный'] as const).map(item=><button key={item} className={risk===item?'active':''} onClick={()=>setRisk(item)}>{item}</button>)}</div><span>{shown.length} стратегий</span></div><section className="market-grid">{shown.map(offer=><OfferCard key={offer.id} offer={offer} saved={saved.includes(offer.id)} application={applicationFor(offer)} save={()=>setSaved(items=>items.includes(offer.id)?items.filter(id=>id!==offer.id):[...items,offer.id])} open={()=>setSelected(offer)}/>)}</section>
    {selected&&<OfferModal offer={selected} application={applicationFor(selected)} close={()=>setSelected(null)} message={()=>message(selected)} apply={()=>setApplying(selected)} fund={()=>navigate('/investor/funds')} />}{applying&&<ApplicationModal offer={applying} close={()=>setApplying(null)} submit={application=>{saveOfferApplications([...readOfferApplications(),application]);setApplying(null);setSelected(applying)}}/>}</main>
}
function OfferCard({offer,saved,application,save,open}:{offer:Offer;saved:boolean;application?:OfferApplication;save:()=>void;open:()=>void}){return <article className="market-card"><div className={`market-cover ${offer.visual}`}><div className="cover-grid"/><span>{offer.team}</span><button aria-label="В избранное" className={saved?'saved':''} onClick={save}><Heart fill={saved?'currentColor':'none'}/></button><div className="cover-graph"/></div><div className="market-card-body"><div className="card-title"><div><p>{offer.risk}</p><h3>{offer.name}</h3></div></div><p className="card-description">{offer.description}</p><div className="card-terms"><div><span>Доходность</span><b>{offer.yield}</b></div><div><span>Минимум</span><b>{offer.minimum}<small> USDT</small></b></div><div><span>Срок</span><b>{offer.term}</b></div></div><div className="card-footer"><span><Users/> {offer.investors} инвесторов</span><button className={application?'applied':''} onClick={open}>{application?<><Check/>{statusText[application.status]}</>:<>Подробнее<ArrowUpRight/></>}</button></div></div></article>}
function OfferModal({offer,application,close,message,apply,fund}:{offer:Offer;application?:OfferApplication;close:()=>void;message:()=>void;apply:()=>void;fund:()=>void}){const [document,setDocument]=useState(false);const signed=()=>{if(application)saveOfferApplications(readOfferApplications().map(item=>item.id===application.id?{...item,status:'funding'}:item))};return <div className="market-modal"><button className="modal-backdrop" onClick={close}/><section><button className="modal-close" onClick={close}><X/></button><div className={`modal-cover ${offer.visual}`}><span>{offer.team}</span><div className="cover-graph"/></div><div className="modal-content">{document?<><p className="eyebrow">УСЛОВИЯ И ДОГОВОР</p><h2>Условия {offer.name}</h2><div className="conditions"><span>Срок участия <b>{offer.term}</b></span><span>Минимальная сумма <b>{offer.minimum} USDT</b></span><span>Порядок вывода <b>{offer.withdrawal}</b></span><span>Комиссия компании <b>{offer.fee}</b></span><span>Расчётный период <b>Ежемесячно</b></span></div><button className="offer-document" onClick={()=>setDocument(false)}>← К описанию стратегии</button></>:<><p className="eyebrow">ИНВЕСТИЦИОННОЕ ПРЕДЛОЖЕНИЕ</p><h2>{offer.name}</h2><p className="modal-description">{offer.description}</p><div className="modal-highlights"><div><b>{offer.yield}</b><span>доходность за 12 месяцев</span></div><div className="coverage-tip"><b>{offer.cover}</b><span>покрытие escrow <Info/></span><aside>Это отношение залога на escrow-счёте к начисленной комиссии. Покрытие от 100% означает, что комиссия обеспечена; капитал инвестора хранится отдельно.</aside></div><div><b>{offer.investors}</b><span>активных инвесторов</span></div></div><div className="conditions"><p>ОСНОВНЫЕ УСЛОВИЯ</p><span>Минимальная сумма <b>{offer.minimum} USDT</b></span><span>Срок участия <b>{offer.term}</b></span><span>Вывод средств <b>{offer.withdrawal}</b></span><span>Комиссия компании <b>{offer.fee}</b></span></div><div className="modal-tags">{offer.tags.map(tag=><span key={tag}>{tag}</span>)}</div><button className="offer-document" onClick={()=>setDocument(true)}><FileText/>Просмотреть условия и договор<ArrowUpRight/></button></>}{application?<ApplicationState application={application} onSign={signed} onFund={fund} onMessage={message}/>:<div className="modal-actions"><button className="write-lead" onClick={message}><MessageCircle/>Написать тимлиду</button><button className="market-apply" onClick={apply}>Подать заявку</button></div>}<p className="modal-foot"><Clock3/>Заявка рассматривается тимлидом в течение рабочего дня.</p></div></section></div>}
function ApplicationState({application,onSign,onFund,onMessage}){return <section className="application-state"><p>ЗАЯВКА НА {application.amount} USDT · {application.wallet}</p><b>{statusText[application.status]}</b><span>{application.status==='review'&&'Тимлид проверяет заявку. До согласования деньги не блокируются.'}{application.status==='clarification'&&(application.decisionNote||'Тимлид запросил уточнение условий.')}{application.status==='contract_ready'&&'Индивидуальный договор сформирован. Ознакомьтесь с ним и подпишите через Trigonum ID.'}{application.status==='funding'&&'Договор подписан. Пополните инвестицию с выбранного кошелька — после подтверждения она активируется.'}{application.status==='declined'&&(application.decisionNote||'Вы можете обсудить причину с тимлидом и подать новую заявку.')}</span><div>{application.status==='contract_ready'&&<button className="market-apply" onClick={onSign}>Подписать договор</button>}{application.status==='funding'&&<button className="market-apply" onClick={onFund}><WalletCards/>Пополнить инвестицию</button>}{(application.status==='clarification'||application.status==='declined')&&<button className="write-lead" onClick={onMessage}><MessageCircle/>Написать тимлиду</button>}</div></section>}
function ApplicationModal({offer,close,submit}){const [amount,setAmount]=useState(offer.minimum),[wallet,setWallet]=useState('Основной USDT · TRC-20'),[note,setNote]=useState(''),[accepted,setAccepted]=useState(false);const valid=toAmount(amount)>=toAmount(offer.minimum)&&accepted;return <div className="market-modal application-modal"><button className="modal-backdrop" onClick={close}/><section><button className="modal-close" onClick={close}><X/></button><div className="application-form"><p className="eyebrow">НОВАЯ ЗАЯВКА</p><h2>Участие в {offer.name}</h2><span>Укажите сумму и кошелёк. Средства не списываются до подписания индивидуального договора.</span><label>Сумма участия, USDT<input value={amount} inputMode="decimal" onChange={event=>setAmount(event.target.value)} /></label>{toAmount(amount)<toAmount(offer.minimum)&&<small className="form-error">Минимальная сумма — {offer.minimum} USDT</small>}<label>Источник средств<select value={wallet} onChange={event=>setWallet(event.target.value)}><option>Основной USDT · TRC-20</option><option>Ethereum · ERC-20</option><option>Биржевой кошелёк · Binance</option></select></label><label>Комментарий для тимлида <textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Необязательно" /></label><label className="terms-check"><input type="checkbox" checked={accepted} onChange={event=>setAccepted(event.target.checked)}/><span>Я ознакомился с условиями, рисками и порядком вывода средств.</span></label><footer><button className="write-lead" onClick={close}>Отмена</button><button className="market-apply" disabled={!valid} onClick={()=>submit({id:`app-${Date.now()}`,offerId:offer.id,offerName:offer.name,team:offer.team,investor:'Павел Орлов',initials:'ПО',amount:amount.replace(/\s/g,''),wallet,note,createdAt:'Только что',status:'review'})}>Отправить заявку <ArrowUpRight/></button></footer></div></section></div>}
